//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GtiTeste.AppWebForms.ClienteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteContract", Namespace="http://schemas.datacontract.org/2004/07/GtiTeste.WCF.Entidades")]
    [System.SerializableAttribute()]
    public partial class ClienteContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataExpedicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GtiTeste.AppWebForms.ClienteService.EnderecoContract EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgaoExpedicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpf {
            get {
                return this.CpfField;
            }
            set {
                if ((object.ReferenceEquals(this.CpfField, value) != true)) {
                    this.CpfField = value;
                    this.RaisePropertyChanged("Cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataExpedicao {
            get {
                return this.DataExpedicaoField;
            }
            set {
                if ((this.DataExpedicaoField.Equals(value) != true)) {
                    this.DataExpedicaoField = value;
                    this.RaisePropertyChanged("DataExpedicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GtiTeste.AppWebForms.ClienteService.EnderecoContract Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCivil {
            get {
                return this.EstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoCivilField, value) != true)) {
                    this.EstadoCivilField = value;
                    this.RaisePropertyChanged("EstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgaoExpedicao {
            get {
                return this.OrgaoExpedicaoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgaoExpedicaoField, value) != true)) {
                    this.OrgaoExpedicaoField = value;
                    this.RaisePropertyChanged("OrgaoExpedicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RG {
            get {
                return this.RGField;
            }
            set {
                if ((object.ReferenceEquals(this.RGField, value) != true)) {
                    this.RGField = value;
                    this.RaisePropertyChanged("RG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnderecoContract", Namespace="http://schemas.datacontract.org/2004/07/GtiTeste.WCF.Entidades")]
    [System.SerializableAttribute()]
    public partial class EnderecoContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cep {
            get {
                return this.CepField;
            }
            set {
                if ((object.ReferenceEquals(this.CepField, value) != true)) {
                    this.CepField = value;
                    this.RaisePropertyChanged("Cep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logradouro {
            get {
                return this.LogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroField, value) != true)) {
                    this.LogradouroField = value;
                    this.RaisePropertyChanged("Logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoOperacaoDTO", Namespace="http://schemas.datacontract.org/2004/07/GtiTeste.Business.DTO")]
    [System.SerializableAttribute()]
    public partial class RetornoOperacaoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] MensagensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OperacaoValidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Mensagens {
            get {
                return this.MensagensField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagensField, value) != true)) {
                    this.MensagensField = value;
                    this.RaisePropertyChanged("Mensagens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacaoValida {
            get {
                return this.OperacaoValidaField;
            }
            set {
                if ((this.OperacaoValidaField.Equals(value) != true)) {
                    this.OperacaoValidaField = value;
                    this.RaisePropertyChanged("OperacaoValida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoContract", Namespace="http://schemas.datacontract.org/2004/07/GtiTeste.WCF.Entidades")]
    [System.SerializableAttribute()]
    public partial class EstadoContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiglaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sigla {
            get {
                return this.SiglaField;
            }
            set {
                if ((object.ReferenceEquals(this.SiglaField, value) != true)) {
                    this.SiglaField = value;
                    this.RaisePropertyChanged("Sigla");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteService.IClienteSvc")]
    public interface IClienteSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteSvc/ObterClientes", ReplyAction="http://tempuri.org/IClienteSvc/ObterClientesResponse")]
        GtiTeste.AppWebForms.ClienteService.ClienteContract[] ObterClientes(string cpf, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteSvc/ObterClientes", ReplyAction="http://tempuri.org/IClienteSvc/ObterClientesResponse")]
        System.Threading.Tasks.Task<GtiTeste.AppWebForms.ClienteService.ClienteContract[]> ObterClientesAsync(string cpf, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteSvc/Incluir", ReplyAction="http://tempuri.org/IClienteSvc/IncluirResponse")]
        GtiTeste.AppWebForms.ClienteService.RetornoOperacaoDTO Incluir(GtiTeste.AppWebForms.ClienteService.ClienteContract cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteSvc/Incluir", ReplyAction="http://tempuri.org/IClienteSvc/IncluirResponse")]
        System.Threading.Tasks.Task<GtiTeste.AppWebForms.ClienteService.RetornoOperacaoDTO> IncluirAsync(GtiTeste.AppWebForms.ClienteService.ClienteContract cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteSvc/Alterar", ReplyAction="http://tempuri.org/IClienteSvc/AlterarResponse")]
        GtiTeste.AppWebForms.ClienteService.RetornoOperacaoDTO Alterar(System.Guid Id, GtiTeste.AppWebForms.ClienteService.ClienteContract cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteSvc/Alterar", ReplyAction="http://tempuri.org/IClienteSvc/AlterarResponse")]
        System.Threading.Tasks.Task<GtiTeste.AppWebForms.ClienteService.RetornoOperacaoDTO> AlterarAsync(System.Guid Id, GtiTeste.AppWebForms.ClienteService.ClienteContract cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteSvc/Excluir", ReplyAction="http://tempuri.org/IClienteSvc/ExcluirResponse")]
        GtiTeste.AppWebForms.ClienteService.RetornoOperacaoDTO Excluir(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteSvc/Excluir", ReplyAction="http://tempuri.org/IClienteSvc/ExcluirResponse")]
        System.Threading.Tasks.Task<GtiTeste.AppWebForms.ClienteService.RetornoOperacaoDTO> ExcluirAsync(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteSvc/Detalhar", ReplyAction="http://tempuri.org/IClienteSvc/DetalharResponse")]
        GtiTeste.AppWebForms.ClienteService.ClienteContract Detalhar(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteSvc/Detalhar", ReplyAction="http://tempuri.org/IClienteSvc/DetalharResponse")]
        System.Threading.Tasks.Task<GtiTeste.AppWebForms.ClienteService.ClienteContract> DetalharAsync(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteSvc/ObterEstados", ReplyAction="http://tempuri.org/IClienteSvc/ObterEstadosResponse")]
        GtiTeste.AppWebForms.ClienteService.EstadoContract[] ObterEstados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteSvc/ObterEstados", ReplyAction="http://tempuri.org/IClienteSvc/ObterEstadosResponse")]
        System.Threading.Tasks.Task<GtiTeste.AppWebForms.ClienteService.EstadoContract[]> ObterEstadosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteSvcChannel : GtiTeste.AppWebForms.ClienteService.IClienteSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteSvcClient : System.ServiceModel.ClientBase<GtiTeste.AppWebForms.ClienteService.IClienteSvc>, GtiTeste.AppWebForms.ClienteService.IClienteSvc {
        
        public ClienteSvcClient() {
        }
        
        public ClienteSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GtiTeste.AppWebForms.ClienteService.ClienteContract[] ObterClientes(string cpf, string nome) {
            return base.Channel.ObterClientes(cpf, nome);
        }
        
        public System.Threading.Tasks.Task<GtiTeste.AppWebForms.ClienteService.ClienteContract[]> ObterClientesAsync(string cpf, string nome) {
            return base.Channel.ObterClientesAsync(cpf, nome);
        }
        
        public GtiTeste.AppWebForms.ClienteService.RetornoOperacaoDTO Incluir(GtiTeste.AppWebForms.ClienteService.ClienteContract cliente) {
            return base.Channel.Incluir(cliente);
        }
        
        public System.Threading.Tasks.Task<GtiTeste.AppWebForms.ClienteService.RetornoOperacaoDTO> IncluirAsync(GtiTeste.AppWebForms.ClienteService.ClienteContract cliente) {
            return base.Channel.IncluirAsync(cliente);
        }
        
        public GtiTeste.AppWebForms.ClienteService.RetornoOperacaoDTO Alterar(System.Guid Id, GtiTeste.AppWebForms.ClienteService.ClienteContract cliente) {
            return base.Channel.Alterar(Id, cliente);
        }
        
        public System.Threading.Tasks.Task<GtiTeste.AppWebForms.ClienteService.RetornoOperacaoDTO> AlterarAsync(System.Guid Id, GtiTeste.AppWebForms.ClienteService.ClienteContract cliente) {
            return base.Channel.AlterarAsync(Id, cliente);
        }
        
        public GtiTeste.AppWebForms.ClienteService.RetornoOperacaoDTO Excluir(System.Guid Id) {
            return base.Channel.Excluir(Id);
        }
        
        public System.Threading.Tasks.Task<GtiTeste.AppWebForms.ClienteService.RetornoOperacaoDTO> ExcluirAsync(System.Guid Id) {
            return base.Channel.ExcluirAsync(Id);
        }
        
        public GtiTeste.AppWebForms.ClienteService.ClienteContract Detalhar(System.Guid Id) {
            return base.Channel.Detalhar(Id);
        }
        
        public System.Threading.Tasks.Task<GtiTeste.AppWebForms.ClienteService.ClienteContract> DetalharAsync(System.Guid Id) {
            return base.Channel.DetalharAsync(Id);
        }
        
        public GtiTeste.AppWebForms.ClienteService.EstadoContract[] ObterEstados() {
            return base.Channel.ObterEstados();
        }
        
        public System.Threading.Tasks.Task<GtiTeste.AppWebForms.ClienteService.EstadoContract[]> ObterEstadosAsync() {
            return base.Channel.ObterEstadosAsync();
        }
    }
}
